api:
  api_problem:
    enabled: true
    exception_handlers:
      - EsTodosApi\Infrastructure\ExceptionHandler\Strategy\NotFoundExceptionHandler
      - EsTodosApi\Infrastructure\ExceptionHandler\Strategy\NotFoundHttpExceptionStrategy
      - EsTodosApi\Infrastructure\ExceptionHandler\Strategy\UniqueConstraintViolationExceptionStrategy
